authapp/urls.py
from django.urls import path

# from .views import BaseView, ProductDetailView, CategoryDetailView, CartView, AddToCartView, DeleteFromCartView, ChangeQTYView, ChangeSizeView, CheckoutView, MakeOrderView
import authapp.views as authapp
app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),

]

sneakersoftravel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('authapp.urls', namespace='authapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models

from mainapp.models import *
# Create your models here.

authapp/forms.py
from django import forms

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from mainapp.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'password1',
            'password2',
            'email',
            'first_name',
            'last_name',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

authapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from mainapp.views import *

from authapp.forms import LoginForm, RegisterForm



def login(request):
    categories = Category.objects.get_categories_for_left_sidebar()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('base'))
    else:
        form = LoginForm()
    content = {
        'title': 'Авторизация',
        'form': form,
        'categories': categories,
    }
    return render(request, 'authapp/login.html', content)


def register(request):
    categories = Category.objects.get_categories_for_left_sidebar()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно зарегистрировались!')
            return HttpResponseRedirect(reverse('authapp:login'))
    else:
        form = RegisterForm()
    content = {
        'title': 'Регистрация',
        'form': form,
        'categories': categories,
    }
    return render(request, 'authapp/register.html', content)


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('base'))

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}

{% load static %}
{% block content %}

    <header class="bg-dark py-1">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Авторизация</h1>
                <p class="lead fw-normal text-white-50 mb-0">Пожалуйста, введита данные ниже для авторизации</p>
            </div>
        </div>
    </header>
    <div class="support_form">
        <form method="post" class="" style="width: 28%; margin-left: auto; margin-right: auto; margin-top: 50px;">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="{% url 'authapp:register' %}" class="btn btn-outline-dark" style="float: left;">Зарегистрироваться</a>
            <button class="btn btn-dark" name="submit" style="float: right;">Войти</button>
        </form>

    </div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}

{% block content %}

    <header class="bg-dark py-1">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Регистрация</h1>
                <p class="lead fw-normal text-white-50 mb-0">Пожалуйста, введита данные ниже для регистрации</p>
            </div>
        </div>
    </header>
    <form method="post" class="pb-5" style="width: 28%; margin-left: auto; margin-right: auto; margin-top: 50px;">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'authapp:login' %}" class="btn btn-outline-dark" style="float: left;">Уже есть аккаунт?</a>
        <button class="blue-button send btn btn-dark" style="float: right;" name="submit">Зарегистрироваться</button>
    </form>
{% endblock %}