authapp/urls.py
from django.urls import path

# from .views import BaseView, ProductDetailView, CategoryDetailView, CartView, AddToCartView, DeleteFromCartView, ChangeQTYView, ChangeSizeView, CheckoutView, MakeOrderView
import authapp.views as authapp
app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('logout/', authapp.logout, name='logout'),

]

mainapp/urls.py
from django.urls import path

from . import views
from .views import BaseView, ProductDetailView, CategoryDetailView, CartView, AddToCartView, DeleteFromCartView, \
    ChangeQTYView, ChangeSizeView, CheckoutView, MakeOrderView, About

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('change-size/<str:ct_model>/<str:slug>/', ChangeSizeView.as_view(), name='change_size'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),

    path('about/', About.as_view(), name='about'),

]

sneakersoftravel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('authapp.urls', namespace='authapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )

mainapp/views.py
from django.db import transaction
from django.shortcuts import render
from django.template import loader
from django.views.generic import DetailView, View
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from .models import Sneakers, Boots, Category, LatestProducts, Customer, Cart, CartProduct
from .mixins import CategoryDetailMixin, CartMixin
from .forms import OrderForm
from .utility import recalic_cart


class BaseView(CartMixin, View):
    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        products = LatestProducts.objects.get_products_for_main_page(
            'sneakers', 'boots', with_respect_to='sneakers'
        )
        context = {
            'categories': categories,
            'products': products,
            'cart': self.cart,
        }
        return render(request, 'mainapp/base.html', context)


class ProductDetailView(CartMixin, CategoryDetailMixin, DetailView):

    CT_MODEL_MODEL_CLASS = {
        'sneakers': Sneakers,
        'boots': Boots
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'product'
    template_name = 'mainapp/product_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ct_model'] = self.model._meta.model_name
        context['cart'] = self.cart
        return context


class CategoryDetailView(CartMixin, CategoryDetailMixin, DetailView):

    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'mainapp/category_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = self.cart
        return context


class AddToCartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product, created = CartProduct.objects.get_or_create(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        if created:
            self.cart.products.add(cart_product)
        recalic_cart(self.cart)
        messages.add_message(request, messages.INFO, "Товар успешно добавлен")
        return HttpResponseRedirect('/cart/')


class DeleteFromCartView(CartMixin, View):
    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        self.cart.products.remove(cart_product)
        cart_product.delete()
        recalic_cart(self.cart)
        messages.add_message(request, messages.INFO, "Товар успешно удален")
        return HttpResponseRedirect('/cart/')


class ChangeQTYView(CartMixin, View):
    def post(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        qty = int(request.POST.get('qty'))
        cart_product.qty = qty
        cart_product.save()
        recalic_cart(self.cart)
        messages.add_message(request, messages.INFO, "Количество успешно изменено")
        return HttpResponseRedirect('/cart/')


class ChangeSizeView(CartMixin, View):
    def post(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        size = int(request.POST.get('size'))
        cart_product.size = size
        cart_product.save()
        recalic_cart(self.cart)
        messages.add_message(request, messages.INFO, "Размер успешно выбран")
        return HttpResponseRedirect('/cart/')


class CartView(CartMixin, View):
    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        context = {
            'cart': self.cart,
            'categories': categories
        }
        return render(request, 'mainapp/cart.html', context)


class CheckoutView(CartMixin, View):
    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        form = OrderForm(request.POST or None)
        context = {
            'cart': self.cart,
            'categories': categories,
            'form': form
        }
        return render(request, 'mainapp/checkout.html', context)


class MakeOrderView(CartMixin, View):

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST or None)
        customer = Customer.objects.get(user=request.user)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.customer = customer
            new_order.first_name = form.cleaned_data['first_name']
            new_order.last_name = form.cleaned_data['last_name']
            new_order.phone = form.cleaned_data['phone']
            new_order.address = form.cleaned_data['address']
            new_order.buying_type = form.cleaned_data['buying_type']
            new_order.order_date = form.cleaned_data['order_date']
            new_order.comment = form.cleaned_data['comment']
            new_order.save()
            self.cart.in_order = True
            self.cart.save()
            new_order.cart = self.cart
            new_order.save()
            customer.orders.add(new_order)
            messages.add_message(request, messages.INFO, 'Спасибо за заказ! Менеджер свяжется с Вами')
            return HttpResponseRedirect('/')
        return HttpResponseRedirect('/checkout/')


class About(View):
    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        context = {
            'categories': categories,
        }
        return render(request, 'mainapp/about.html', context)

mainapp/templates/mainapp/about.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}

<header class="bg-dark py-1">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">О компании</h1>
            <p class="lead fw-normal text-white-50 mb-0"></p>
        </div>
    </div>
</header>

<div style="padding: 25px; z-index: 1;">
<div>
    <div class="rounded" style="float:left; margin-left: 20em; background-image: url(/media/about-bg.jpg); width: 420px; height: 560px;"></div>
    <div style="margin-left: 48em;" class="center">
        <h1 style="margin-bottom: -5px;"><b>Sneakers of Travel</b></h1>
        <hr>
        <p style="font-size: 20px;"> Осуществляем достаку по странам СНГ</p>
        <p style="font-size: 20px;"> Наша цель - подарить людям возможность заказать красивую брендовую обувь</p>
        <p style="font-size: 20px;" class="bi bi-envelope">  xMolod0yx.Arseny@yandex.ru </p>
        <p style="font-size: 20px;" class="bi bi-telephone">  +12123123123 </p>
    </div>
    </div>
</div>



{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>SNEAKERS OF TRAVEL</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">

    <link type="image/x-icon" href="{% static '/favicon.svg' %}" rel="shortcut icon">
    <link type="Image/x-icon" href="{% static '/favicon.svg' %}" rel="icon">

    <link href="{% static '/fonts/' %}" rel="stylesheet" type="text/css">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="//code.jivo.ru/widget/f5h8CoqVFf" async></script></head>
<body style="overflow-x: hidden">
<div style="overflow: hidden; display: flex; flex-direction: column; min-height: 100vh; ">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="z-index: 3;">
        <div class="container px-4 px-lg-4">
            <a class="navbar-brand" href="{% url 'base' %}"><img src="/static/logo.svg" style="width: 100px; height: 40px; margin-right: -37px;"> <b style="color: #282828; font-size: 18px;">sneakers of travel</b></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                {% for category in categories %}
                    <li class="nav-item"><a class="nav-link" href="{{ category.url }}">{{ category.name }}</a></li>
                {% endfor %}
                <li class="nav-item"><a class="nav-link" href="/about">О компании</a></li>
            </ul>


            <ul class="navbar-nav">
                <li class="nav-item float-right d-flex float-right">
                    {% if user.is_authenticated %}
                        <a class="nav-link bi bi-box-arrow-left" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Нажмите для выхода" href="{% url 'authapp:logout' %}"> {{ user.username }}</a>
                    {% else %}
                        <a class="nav-link bi bi-box-arrow-in-right" href="{% url 'authapp:login' %}"> Войти</a>
                    {% endif %}

                    <a class="nav-link" href="{% url 'cart' %}">
                        <i class="bi-cart-fill me-1 dark"></i>
                        Корзина
                        {% if user.is_authenticated %}
                        <sup><div class="badge text-white bg-dark rounded-circle">{{ cart.products.count }}</div></sup>
                        {% else %}
                        <div class="badge text-white rounded-circle bg-cart">{{ cart.products.count }}</div>
                        {% endif %}

                    </a>
                </li>
            </ul>
        </div>
</div>
</nav>
<!-- Header-->
{% block content %}

    <header class="bg-dark py-5 asd" style=" z-index: 3; background-image: url(/media/bg-nike-opacity.png); background-position: center; background-size: cover; ">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-secondary  alert-dismissible fade show" role="alert"
                     style="margin-top: -3rem!important; text-align: center; width: 60%; margin: auto;">
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </button>
                </div>
            {% endfor %}
        {% endif %}

        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">SNEAKERS OF TRAVEL</h1>
                <p class="lead fw-normal text-white-50 mb-0">С комфортом по городу!</p>
            </div>
        </div>
    </header>


    <!-- Section-->


    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">
                {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100 shadow-sm">
                            <!-- Product image-->
                            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}"
                                                                                      class="card-img-top"></a>
                                    </div>
                                    <div class="carousel-item">
                                        <a href="{{ product.get_absolute_url }}"><img
                                                src="{{ product.imagesecond.url }}" class="card-img-top"></a>
                                    </div>
                                    <div class="carousel-item">
                                        <a href="{{ product.get_absolute_url }}"><img
                                                src="{{ product.imagethird.url }}" class="card-img-top"></a>
                                    </div>
                                </div>
                            </div>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <a href="{{ product.get_absolute_url }}" style="text-decoration: none;"><h5
                                            class="fw-bolder"
                                            style="color: black; font-size: 18px;">{{ product.title }}</h5></a>
                                    <!-- Product price-->
                                    <h6>{{ product.price }} руб.</h6>
                                </div>
                                <div>
                                    Пол: {{ product.gender }}<br>
                                    Сезон: {{ product.season }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                            href="{{ product.get_absolute_url }}">Подробнее</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>

    </section>

{% endblock content %}
<footer class="py-5 bg-dark" style="overflow:hidden; margin-top: auto; z-index: 3;">
    <div class="container"><p class="m-0 text-center text-white">&copy; Sneakers of Travel 2022</p></div>
</footer>
</div>
<!-- Bootstrap core JS-->
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>

<!-- Core theme JS-->
<script src="js/scripts.js"></script>

</body>
</html>

mainapp/templates/mainapp/category_detail.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <header class="bg-dark py-5 asd"
            style="background-image: url(/media/bg-nike-opacity.png); background-position: center; background-size: cover; ">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-secondary  alert-dismissible fade show" role="alert"
                     style="margin-top: -3rem!important; text-align: center; width: 60%; margin: auto;">
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">{{ category.name }}</h1>
                <p class="lead fw-normal text-white-50 mb-0">Вон та пара тебе точно понравится</p>
            </div>
        </div>
    </header>

    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">
                {% for product in category_products %}
                    <div class="col mb-5">
                        <div class="card h-100 shadow">
                            <!-- Product image-->
                            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}"
                                                                                      class="card-img-top"></a>
                                    </div>
                                    <div class="carousel-item">
                                        <a href="{{ product.get_absolute_url }}"><img
                                                src="{{ product.imagesecond.url }}" class="card-img-top"></a>
                                    </div>
                                    <div class="carousel-item">
                                        <a href="{{ product.get_absolute_url }}"><img src="{{ product.imagethird.url }}"
                                                                                      class="card-img-top"></a>
                                    </div>
                                </div>
                            </div>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <a style="text-decoration: none;" href="{{ product.get_absolute_url }}"><h5
                                            class="fw-bolder"
                                            style="font-size: 18px; color: black;">{{ product.title }}</h5></a>
                                    <!-- Product price-->
                                    <h6>{{ product.price }} руб.</h6>
                                </div>
                                <div>
                                    Пол: {{ product.gender }}<br>
                                    Сезон: {{ product.season }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">

                                {% if user.is_authenticated %}
                                    <div class="text-center">
                                        <a class="btn btn-outline-dark mt-auto"
                                           href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                                            Добавить в корзину
                                        </a>
                                    </div>
                                {% endif %}
                                {% if not user.is_authenticated %}
                                    <div class="text-center">
                                        <a class="btn btn-outline-dark mt-auto"
                                           href="{% url 'authapp:login' %}">
                                            Добавить в корзину
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}

mainapp/templates/mainapp/checkout.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <header class="bg-dark py-3">

        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                    <h3 class="text-center">Оформление заказа</h3>
            </div>
        </div>
    </header>
<div style="width: 80%; margin: auto;" class="bg-light border rounded mb-5 mt-5">

    <table class="table">
        <thead>
        <tr>
          <th scope="col">Наименование</th>
          <th scope="col">Размер</th>
          <th scope="col">Изображение</th>
          <th scope="col">Цена</th>
          <th scope="col">Кол-во</th>
          <th scope="col">Общая цена</th>

        </tr>
        </thead>
        <tbody>
        {% for item in cart.products.all %}
        <tr>
            <th scope="row">{{ item.content_object.title }}</th>
            <th scope="row">{{ item.size }}</th>
            <td class="w-25"><img  src="{{ item.content_object.image.url }}" class="img-fluid"></td>
            <td>{{ item.content_object.price }}
            <td>{{ item.qty }}</td>
            <td>{{ item.final_price }} руб.</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="3"></td>
            <td>Итого:</td>
            <td>{{ cart.total_products }}</td>
            <td>{{ cart.final_price }} руб.</td>

        </tr>

        </tbody>
    </table>
</div>

<div style="width: 60%; margin: auto;" class="bg-light border rounded mb-5">
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="POST">
  {% csrf_token %}
    <div style="width: 70%; margin: auto;">
        {{ form|crispy }}
    </div>
  <div style="text-align: center;"><input type="submit" class="btn btn-outline-dark btn-block mb-3 mt-3" values="Оформить заказ"></div>
</form>
</div>
{% endblock content %}

mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %}
{% load specifications %}

{% block content %}
        <header class="bg-dark py-3"
            style="background-image: url(/media/bg-cart-opacity.jpg); background-position: center; background-size: cover;">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-secondary  alert-dismissible fade show" role="alert"
                     style="margin-top: -3rem!important; text-align: center; width: 60%; margin: auto;">
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-black">
                <h5 class="display-4 fw-bolder">{{ product.title }}</h5>
{#                <p class="lead fw-normal text-white-50 mb-0">{{ product.title }}</p>#}
            </div>
        </div>
    </header>
    <div style="width: 85%; margin: auto;" class="bg-light border border-dark rounded mb-4 mt-4 pb-4 pt-4">

        <div class="row">
            <div class="col-md-4">
                <div id="carouselExampleControls" class="carousel carousel-dark slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{{ product.image.url }}" class="card-img-top">
                        </div>
                        <div class="carousel-item">
                            <img src="{{ product.imagesecond.url }}" class="card-img-top">
                        </div>
                        <div class="carousel-item">
                            <img src="{{ product.imagethird.url }}" class="card-img-top">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Предыдущий</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Следующий</span>
                    </button>
                </div>
            </div>
            <div class="col-md-8">
                <h5 style="text-align: center;">О товаре: </h5>
                <p class="m-2">{{ product.description }}</p>
                <hr>
                <h5 style="text-align: center;">Характеристики: </h5>
                <div class="p-0">
                    {{ product|product_spec }}
                </div>

                {% if user.is_authenticated %}
                    <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %}">
                        <button class="btn btn-outline-dark mt-auto">Добавить в корзину</button>
                    </a>
                {% endif %}
                {% if not user.is_authenticated %}
                    <a href="{% url 'authapp:login' %}">
                        <button class="btn btn-outline-dark mt-auto">Авторизируйтесь для добавления в корзину</button>
                    </a><h5 style="padding-right: 8em; float: right">Цена: {{ product.price }} руб.</h5>
                {% endif %}
            </div>
        </div>


    </div>

{% endblock content %}

mainapp/templates/mainapp/summer_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Рекомендуемый сезон для обуви</td>
      <td>{{ product.season }}</td>
    </tr>
      <tr>
      <td>Пол</td>
      <td>{{ product.gender }}</td>
    </tr>
      <tr>
      <td>Материал верха</td>
      <td>{{ product.top_material }}</td>
    </tr>
      <tr>
      <td>Материал подошвы</td>
      <td>{{ product.sole_material }}</td>
    </tr>
  </tbody>
</table>

mainapp/templates/mainapp/winter_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Рекомендуемый сезон для обуви</td>
      <td>{{ product.season }}</td>
    </tr>
      <tr>
      <td>Пол</td>
      <td>{{ product.gender }}</td>
    </tr>
      <tr>
      <td>Материал верха</td>
      <td>{{ product.top_material }}</td>
    </tr>
      <tr>
      <td>Материал подошвы</td>
      <td>{{ product.sole_material }}</td>
    </tr>
  </tbody>
</table>